# Generated by Django 4.2.1 on 2023-09-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoEvento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endereco',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
