# Generated by Django 4.2.1 on 2023-10-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoEvento', '0002_endereco_excluido_endereco_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidademedida',
            name='sigla',
            field=models.CharField(default='', max_length=3),
        ),
    ]
