# Generated by Django 4.2.1 on 2023-10-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoEvento', '0002_itemlocacao_custo_unitario'),
        ('GestaoEvento', '0003_unidademedida_sigla'),
    ]

    operations = [
    ]
