# Generated by Django 4.2.1 on 2023-11-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoEvento', '0003_unidademedida_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidademedida',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
