# Generated by Django 4.2.1 on 2023-11-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoEvento', '0005_rename_custo_unidade_ingrediente_custo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='observacao',
            field=models.TextField(default=None),
        ),
    ]
