# Generated by Django 4.2.1 on 2023-11-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoEvento', '0006_prato_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='rendimento',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
