# Generated by Django 4.2.1 on 2023-12-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoEvento', '0007_alter_prato_rendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentopratoaux',
            name='rateio',
            field=models.IntegerField(default=0),
        ),
    ]
