# Generated by Django 4.2.1 on 2023-06-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoEvento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='itemlocacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='prato',
            name='usuario',
        ),
    ]
